// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package io.github.exilonx.attested_secure_keys

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MessagesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Where the private key material lives. Higher == stronger assurance. */
enum class PgSecurityLevel(val raw: Int) {
  STRONG_BOX(0),
  TRUSTED_ENVIRONMENT(1),
  SECURE_ENCLAVE(2),
  SOFTWARE(3),
  UNKNOWN(4);

  companion object {
    fun ofRaw(raw: Int): PgSecurityLevel? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * What proof of hardware origin the platform can produce for a key.
 *
 * `appleAppAssert` is an App Attest *assertion* (per-session, no cert chain),
 * produced after the one-time `appleAppAttest` registration to respect Apple's
 * attestation rate limits — verified against the key registered at attest time.
 */
enum class PgAttestationType(val raw: Int) {
  ANDROID_KEY_ATTESTATION(0),
  APPLE_APP_ATTEST(1),
  NONE(2),
  APPLE_APP_ASSERT(3);

  companion object {
    fun ofRaw(raw: Int): PgAttestationType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** User-presence/verification requirement enforced by the OS on key use. */
enum class PgUserAuthType(val raw: Int) {
  NONE(0),
  DEVICE_CREDENTIAL(1),
  BIOMETRIC_STRONG(2),
  BIOMETRIC_OR_CREDENTIAL(3);

  companion object {
    fun ofRaw(raw: Int): PgUserAuthType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Encoding of the verbatim attestation artifact handed to the server. */
enum class PgAttestationEncoding(val raw: Int) {
  X5C_DER(0),
  CBOR(1),
  JWT(2);

  companion object {
    fun ofRaw(raw: Int): PgAttestationEncoding? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** iOS keychain accessibility for the persisted (encrypted) key blob. */
enum class PgIosAccessibility(val raw: Int) {
  WHEN_UNLOCKED_THIS_DEVICE_ONLY(0),
  AFTER_FIRST_UNLOCK_THIS_DEVICE_ONLY(1);

  companion object {
    fun ofRaw(raw: Int): PgIosAccessibility? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * EC P-256 public key in JWK form (RFC 7517). `x`/`y` are base64url, unpadded.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PgJwk (
  val kty: String,
  val crv: String,
  val x: String,
  val y: String,
  val alg: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PgJwk {
      val kty = pigeonVar_list[0] as String
      val crv = pigeonVar_list[1] as String
      val x = pigeonVar_list[2] as String
      val y = pigeonVar_list[3] as String
      val alg = pigeonVar_list[4] as String
      return PgJwk(kty, crv, x, y, alg)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      kty,
      crv,
      x,
      y,
      alg,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PgJwk
    return MessagesPigeonUtils.deepEquals(this.kty, other.kty) && MessagesPigeonUtils.deepEquals(this.crv, other.crv) && MessagesPigeonUtils.deepEquals(this.x, other.x) && MessagesPigeonUtils.deepEquals(this.y, other.y) && MessagesPigeonUtils.deepEquals(this.alg, other.alg)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.kty)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.crv)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.x)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.y)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.alg)
    return result
  }
  override fun toString(): String {
    return "PgJwk(kty=$kty, crv=$crv, x=$x, y=$y, alg=$alg)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PgUserAuthPolicy (
  val type: PgUserAuthType,
  /** 0 => per-use authentication (re-auth on every signature). */
  val validityMillis: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PgUserAuthPolicy {
      val type = pigeonVar_list[0] as PgUserAuthType
      val validityMillis = pigeonVar_list[1] as Long
      return PgUserAuthPolicy(type, validityMillis)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      type,
      validityMillis,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PgUserAuthPolicy
    return MessagesPigeonUtils.deepEquals(this.type, other.type) && MessagesPigeonUtils.deepEquals(this.validityMillis, other.validityMillis)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.type)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.validityMillis)
    return result
  }
  override fun toString(): String {
    return "PgUserAuthPolicy(type=$type, validityMillis=$validityMillis)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PgAndroidKeyOptions (
  val strongBoxPreferred: Boolean,
  val requireStrongBox: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PgAndroidKeyOptions {
      val strongBoxPreferred = pigeonVar_list[0] as Boolean
      val requireStrongBox = pigeonVar_list[1] as Boolean
      return PgAndroidKeyOptions(strongBoxPreferred, requireStrongBox)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      strongBoxPreferred,
      requireStrongBox,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PgAndroidKeyOptions
    return MessagesPigeonUtils.deepEquals(this.strongBoxPreferred, other.strongBoxPreferred) && MessagesPigeonUtils.deepEquals(this.requireStrongBox, other.requireStrongBox)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.strongBoxPreferred)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.requireStrongBox)
    return result
  }
  override fun toString(): String {
    return "PgAndroidKeyOptions(strongBoxPreferred=$strongBoxPreferred, requireStrongBox=$requireStrongBox)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PgIosKeyOptions (
  val accessibility: PgIosAccessibility,
  val accessGroup: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PgIosKeyOptions {
      val accessibility = pigeonVar_list[0] as PgIosAccessibility
      val accessGroup = pigeonVar_list[1] as String?
      return PgIosKeyOptions(accessibility, accessGroup)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      accessibility,
      accessGroup,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PgIosKeyOptions
    return MessagesPigeonUtils.deepEquals(this.accessibility, other.accessibility) && MessagesPigeonUtils.deepEquals(this.accessGroup, other.accessGroup)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.accessibility)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.accessGroup)
    return result
  }
  override fun toString(): String {
    return "PgIosKeyOptions(accessibility=$accessibility, accessGroup=$accessGroup)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PgGenerateKeyRequest (
  val alias: String,
  val minSecurityLevel: PgSecurityLevel,
  val userAuth: PgUserAuthPolicy,
  val android: PgAndroidKeyOptions,
  val ios: PgIosKeyOptions,
  /**
   * Optional server nonce to embed as the Android key-attestation challenge,
   * bound at key-generation time (Android fixes the challenge at keygen). When
   * null, Android falls back to the alias as a placeholder. iOS ignores this —
   * App Attest binds the nonce later, in [AttestedSecureKeysApi.attest].
   */
  val attestationChallenge: ByteArray? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PgGenerateKeyRequest {
      val alias = pigeonVar_list[0] as String
      val minSecurityLevel = pigeonVar_list[1] as PgSecurityLevel
      val userAuth = pigeonVar_list[2] as PgUserAuthPolicy
      val android = pigeonVar_list[3] as PgAndroidKeyOptions
      val ios = pigeonVar_list[4] as PgIosKeyOptions
      val attestationChallenge = pigeonVar_list[5] as ByteArray?
      return PgGenerateKeyRequest(alias, minSecurityLevel, userAuth, android, ios, attestationChallenge)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      alias,
      minSecurityLevel,
      userAuth,
      android,
      ios,
      attestationChallenge,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PgGenerateKeyRequest
    return MessagesPigeonUtils.deepEquals(this.alias, other.alias) && MessagesPigeonUtils.deepEquals(this.minSecurityLevel, other.minSecurityLevel) && MessagesPigeonUtils.deepEquals(this.userAuth, other.userAuth) && MessagesPigeonUtils.deepEquals(this.android, other.android) && MessagesPigeonUtils.deepEquals(this.ios, other.ios) && MessagesPigeonUtils.deepEquals(this.attestationChallenge, other.attestationChallenge)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.alias)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.minSecurityLevel)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.userAuth)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.android)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.ios)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.attestationChallenge)
    return result
  }
  override fun toString(): String {
    return "PgGenerateKeyRequest(alias=$alias, minSecurityLevel=$minSecurityLevel, userAuth=$userAuth, android=$android, ios=$ios, attestationChallenge=${attestationChallenge?.contentToString()})"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PgGeneratedKey (
  val alias: String,
  val publicJwk: PgJwk,
  val requestedLevel: PgSecurityLevel,
  val effectiveLevel: PgSecurityLevel,
  val attestationType: PgAttestationType,
  val gatedByUserAuth: Boolean,
  val userAuthType: PgUserAuthType
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PgGeneratedKey {
      val alias = pigeonVar_list[0] as String
      val publicJwk = pigeonVar_list[1] as PgJwk
      val requestedLevel = pigeonVar_list[2] as PgSecurityLevel
      val effectiveLevel = pigeonVar_list[3] as PgSecurityLevel
      val attestationType = pigeonVar_list[4] as PgAttestationType
      val gatedByUserAuth = pigeonVar_list[5] as Boolean
      val userAuthType = pigeonVar_list[6] as PgUserAuthType
      return PgGeneratedKey(alias, publicJwk, requestedLevel, effectiveLevel, attestationType, gatedByUserAuth, userAuthType)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      alias,
      publicJwk,
      requestedLevel,
      effectiveLevel,
      attestationType,
      gatedByUserAuth,
      userAuthType,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PgGeneratedKey
    return MessagesPigeonUtils.deepEquals(this.alias, other.alias) && MessagesPigeonUtils.deepEquals(this.publicJwk, other.publicJwk) && MessagesPigeonUtils.deepEquals(this.requestedLevel, other.requestedLevel) && MessagesPigeonUtils.deepEquals(this.effectiveLevel, other.effectiveLevel) && MessagesPigeonUtils.deepEquals(this.attestationType, other.attestationType) && MessagesPigeonUtils.deepEquals(this.gatedByUserAuth, other.gatedByUserAuth) && MessagesPigeonUtils.deepEquals(this.userAuthType, other.userAuthType)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.alias)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.publicJwk)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.requestedLevel)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.effectiveLevel)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.attestationType)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.gatedByUserAuth)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.userAuthType)
    return result
  }
  override fun toString(): String {
    return "PgGeneratedKey(alias=$alias, publicJwk=$publicJwk, requestedLevel=$requestedLevel, effectiveLevel=$effectiveLevel, attestationType=$attestationType, gatedByUserAuth=$gatedByUserAuth, userAuthType=$userAuthType)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PgSignRequest (
  val alias: String,
  val payload: ByteArray,
  val promptTitle: String? = null,
  val promptSubtitle: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PgSignRequest {
      val alias = pigeonVar_list[0] as String
      val payload = pigeonVar_list[1] as ByteArray
      val promptTitle = pigeonVar_list[2] as String?
      val promptSubtitle = pigeonVar_list[3] as String?
      return PgSignRequest(alias, payload, promptTitle, promptSubtitle)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      alias,
      payload,
      promptTitle,
      promptSubtitle,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PgSignRequest
    return MessagesPigeonUtils.deepEquals(this.alias, other.alias) && MessagesPigeonUtils.deepEquals(this.payload, other.payload) && MessagesPigeonUtils.deepEquals(this.promptTitle, other.promptTitle) && MessagesPigeonUtils.deepEquals(this.promptSubtitle, other.promptSubtitle)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.alias)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.payload)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.promptTitle)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.promptSubtitle)
    return result
  }
  override fun toString(): String {
    return "PgSignRequest(alias=$alias, payload=${payload.contentToString()}, promptTitle=$promptTitle, promptSubtitle=$promptSubtitle)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PgSignature (
  /** Raw `R||S`, exactly 64 bytes (JOSE/COSE form, not DER). */
  val rawRS: ByteArray
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PgSignature {
      val rawRS = pigeonVar_list[0] as ByteArray
      return PgSignature(rawRS)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      rawRS,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PgSignature
    return MessagesPigeonUtils.deepEquals(this.rawRS, other.rawRS)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.rawRS)
    return result
  }
  override fun toString(): String {
    return "PgSignature(rawRS=${rawRS.contentToString()})"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PgAttestRequest (
  val alias: String,
  val nonce: ByteArray
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PgAttestRequest {
      val alias = pigeonVar_list[0] as String
      val nonce = pigeonVar_list[1] as ByteArray
      return PgAttestRequest(alias, nonce)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      alias,
      nonce,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PgAttestRequest
    return MessagesPigeonUtils.deepEquals(this.alias, other.alias) && MessagesPigeonUtils.deepEquals(this.nonce, other.nonce)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.alias)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.nonce)
    return result
  }
  override fun toString(): String {
    return "PgAttestRequest(alias=$alias, nonce=${nonce.contentToString()})"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PgAttestation (
  val type: PgAttestationType,
  val encoding: PgAttestationEncoding,
  /** Android: cert chain as base64 DER (leaf first). Apple: x5c if present. */
  val x5c: List<String>,
  /** iOS App Attest CBOR object / assertion bytes; null on Android. */
  val raw: ByteArray? = null,
  val attestedKey: PgJwk,
  val nonce: ByteArray
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PgAttestation {
      val type = pigeonVar_list[0] as PgAttestationType
      val encoding = pigeonVar_list[1] as PgAttestationEncoding
      val x5c = pigeonVar_list[2] as List<String>
      val raw = pigeonVar_list[3] as ByteArray?
      val attestedKey = pigeonVar_list[4] as PgJwk
      val nonce = pigeonVar_list[5] as ByteArray
      return PgAttestation(type, encoding, x5c, raw, attestedKey, nonce)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      type,
      encoding,
      x5c,
      raw,
      attestedKey,
      nonce,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PgAttestation
    return MessagesPigeonUtils.deepEquals(this.type, other.type) && MessagesPigeonUtils.deepEquals(this.encoding, other.encoding) && MessagesPigeonUtils.deepEquals(this.x5c, other.x5c) && MessagesPigeonUtils.deepEquals(this.raw, other.raw) && MessagesPigeonUtils.deepEquals(this.attestedKey, other.attestedKey) && MessagesPigeonUtils.deepEquals(this.nonce, other.nonce)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.type)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.encoding)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.x5c)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.raw)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.attestedKey)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.nonce)
    return result
  }
  override fun toString(): String {
    return "PgAttestation(type=$type, encoding=$encoding, x5c=$x5c, raw=${raw?.contentToString()}, attestedKey=$attestedKey, nonce=${nonce.contentToString()})"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PgKeyInfo (
  val alias: String,
  val publicJwk: PgJwk,
  val securityLevel: PgSecurityLevel,
  val attestationType: PgAttestationType,
  val gatedByUserAuth: Boolean,
  val userAuthType: PgUserAuthType
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PgKeyInfo {
      val alias = pigeonVar_list[0] as String
      val publicJwk = pigeonVar_list[1] as PgJwk
      val securityLevel = pigeonVar_list[2] as PgSecurityLevel
      val attestationType = pigeonVar_list[3] as PgAttestationType
      val gatedByUserAuth = pigeonVar_list[4] as Boolean
      val userAuthType = pigeonVar_list[5] as PgUserAuthType
      return PgKeyInfo(alias, publicJwk, securityLevel, attestationType, gatedByUserAuth, userAuthType)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      alias,
      publicJwk,
      securityLevel,
      attestationType,
      gatedByUserAuth,
      userAuthType,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PgKeyInfo
    return MessagesPigeonUtils.deepEquals(this.alias, other.alias) && MessagesPigeonUtils.deepEquals(this.publicJwk, other.publicJwk) && MessagesPigeonUtils.deepEquals(this.securityLevel, other.securityLevel) && MessagesPigeonUtils.deepEquals(this.attestationType, other.attestationType) && MessagesPigeonUtils.deepEquals(this.gatedByUserAuth, other.gatedByUserAuth) && MessagesPigeonUtils.deepEquals(this.userAuthType, other.userAuthType)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.alias)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.publicJwk)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.securityLevel)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.attestationType)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.gatedByUserAuth)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.userAuthType)
    return result
  }
  override fun toString(): String {
    return "PgKeyInfo(alias=$alias, publicJwk=$publicJwk, securityLevel=$securityLevel, attestationType=$attestationType, gatedByUserAuth=$gatedByUserAuth, userAuthType=$userAuthType)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PgCapabilities (
  val hasStrongBox: Boolean,
  val hasTee: Boolean,
  val hasSecureEnclave: Boolean,
  val supportsKeyAttestation: Boolean,
  val supportsBiometricGating: Boolean,
  val bestAvailableLevel: PgSecurityLevel,
  val androidApiLevel: Long? = null,
  val iosVersion: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PgCapabilities {
      val hasStrongBox = pigeonVar_list[0] as Boolean
      val hasTee = pigeonVar_list[1] as Boolean
      val hasSecureEnclave = pigeonVar_list[2] as Boolean
      val supportsKeyAttestation = pigeonVar_list[3] as Boolean
      val supportsBiometricGating = pigeonVar_list[4] as Boolean
      val bestAvailableLevel = pigeonVar_list[5] as PgSecurityLevel
      val androidApiLevel = pigeonVar_list[6] as Long?
      val iosVersion = pigeonVar_list[7] as String?
      return PgCapabilities(hasStrongBox, hasTee, hasSecureEnclave, supportsKeyAttestation, supportsBiometricGating, bestAvailableLevel, androidApiLevel, iosVersion)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      hasStrongBox,
      hasTee,
      hasSecureEnclave,
      supportsKeyAttestation,
      supportsBiometricGating,
      bestAvailableLevel,
      androidApiLevel,
      iosVersion,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PgCapabilities
    return MessagesPigeonUtils.deepEquals(this.hasStrongBox, other.hasStrongBox) && MessagesPigeonUtils.deepEquals(this.hasTee, other.hasTee) && MessagesPigeonUtils.deepEquals(this.hasSecureEnclave, other.hasSecureEnclave) && MessagesPigeonUtils.deepEquals(this.supportsKeyAttestation, other.supportsKeyAttestation) && MessagesPigeonUtils.deepEquals(this.supportsBiometricGating, other.supportsBiometricGating) && MessagesPigeonUtils.deepEquals(this.bestAvailableLevel, other.bestAvailableLevel) && MessagesPigeonUtils.deepEquals(this.androidApiLevel, other.androidApiLevel) && MessagesPigeonUtils.deepEquals(this.iosVersion, other.iosVersion)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.hasStrongBox)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.hasTee)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.hasSecureEnclave)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.supportsKeyAttestation)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.supportsBiometricGating)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.bestAvailableLevel)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.androidApiLevel)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.iosVersion)
    return result
  }
  override fun toString(): String {
    return "PgCapabilities(hasStrongBox=$hasStrongBox, hasTee=$hasTee, hasSecureEnclave=$hasSecureEnclave, supportsKeyAttestation=$supportsKeyAttestation, supportsBiometricGating=$supportsBiometricGating, bestAvailableLevel=$bestAvailableLevel, androidApiLevel=$androidApiLevel, iosVersion=$iosVersion)"
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PgSecurityLevel.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PgAttestationType.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PgUserAuthType.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PgAttestationEncoding.ofRaw(it.toInt())
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PgIosAccessibility.ofRaw(it.toInt())
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PgJwk.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PgUserAuthPolicy.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PgAndroidKeyOptions.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PgIosKeyOptions.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PgGenerateKeyRequest.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PgGeneratedKey.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PgSignRequest.fromList(it)
        }
      }
      141.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PgSignature.fromList(it)
        }
      }
      142.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PgAttestRequest.fromList(it)
        }
      }
      143.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PgAttestation.fromList(it)
        }
      }
      144.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PgKeyInfo.fromList(it)
        }
      }
      145.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PgCapabilities.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is PgSecurityLevel -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is PgAttestationType -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is PgUserAuthType -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is PgAttestationEncoding -> {
        stream.write(132)
        writeValue(stream, value.raw.toLong())
      }
      is PgIosAccessibility -> {
        stream.write(133)
        writeValue(stream, value.raw.toLong())
      }
      is PgJwk -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is PgUserAuthPolicy -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is PgAndroidKeyOptions -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is PgIosKeyOptions -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is PgGenerateKeyRequest -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is PgGeneratedKey -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is PgSignRequest -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      is PgSignature -> {
        stream.write(141)
        writeValue(stream, value.toList())
      }
      is PgAttestRequest -> {
        stream.write(142)
        writeValue(stream, value.toList())
      }
      is PgAttestation -> {
        stream.write(143)
        writeValue(stream, value.toList())
      }
      is PgKeyInfo -> {
        stream.write(144)
        writeValue(stream, value.toList())
      }
      is PgCapabilities -> {
        stream.write(145)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Every method carries
 * `@TaskQueue(type: TaskQueueType.serialBackgroundThread)`: Keystore /
 * Secure-Enclave work (key generation — seconds on StrongBox —, signing,
 * attestation chain serialization) is heavy and MUST NOT run on the Flutter
 * platform (main/UI) thread, where it would jank or trip an ANR. Pigeon
 * dispatches all annotated methods on a SINGLE shared serial background thread,
 * which both moves them off the UI thread AND serializes secure-hardware access
 * (Keymaster/StrongBox is single-flight anyway), giving deterministic ordering.
 *
 * The biometric prompt is the one thing that must touch the UI thread; the
 * native `sign` implementation re-dispatches `BiometricPrompt.authenticate`
 * (Android) to the main thread itself, so gating still works transparently —
 * callers do nothing.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface AttestedSecureKeysApi {
  /**
   * Generate a NEW non-exportable EC P-256 key in the strongest available
   * secure hardware. Throws (FlutterError code `unsupported_security_level`)
   * if [PgGenerateKeyRequest.minSecurityLevel] cannot be met.
   */
  fun generateKey(request: PgGenerateKeyRequest, callback: (Result<PgGeneratedKey>) -> Unit)
  /**
   * ES256-sign the payload, returning raw 64-byte `R||S`.
   * Triggers the OS biometric/PIN prompt when the key is auth-gated.
   */
  fun sign(request: PgSignRequest, callback: (Result<PgSignature>) -> Unit)
  /** Produce a fresh attestation bound to the supplied server nonce. */
  fun attest(request: PgAttestRequest, callback: (Result<PgAttestation>) -> Unit)
  fun getKeyInfo(alias: String, callback: (Result<PgKeyInfo?>) -> Unit)
  fun containsKey(alias: String): Boolean
  fun deleteKey(alias: String, callback: (Result<Unit>) -> Unit)
  fun listAliases(callback: (Result<List<String>>) -> Unit)
  /** Probe what this device/OS can actually do, before generating anything. */
  fun capabilities(callback: (Result<PgCapabilities>) -> Unit)

  companion object {
    /** The codec used by AttestedSecureKeysApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `AttestedSecureKeysApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: AttestedSecureKeysApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      val taskQueue = binaryMessenger.makeBackgroundTaskQueue()
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.attested_secure_keys.AttestedSecureKeysApi.generateKey$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as PgGenerateKeyRequest
            api.generateKey(requestArg) { result: Result<PgGeneratedKey> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.attested_secure_keys.AttestedSecureKeysApi.sign$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as PgSignRequest
            api.sign(requestArg) { result: Result<PgSignature> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.attested_secure_keys.AttestedSecureKeysApi.attest$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as PgAttestRequest
            api.attest(requestArg) { result: Result<PgAttestation> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.attested_secure_keys.AttestedSecureKeysApi.getKeyInfo$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val aliasArg = args[0] as String
            api.getKeyInfo(aliasArg) { result: Result<PgKeyInfo?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.attested_secure_keys.AttestedSecureKeysApi.containsKey$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val aliasArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.containsKey(aliasArg))
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.attested_secure_keys.AttestedSecureKeysApi.deleteKey$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val aliasArg = args[0] as String
            api.deleteKey(aliasArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.attested_secure_keys.AttestedSecureKeysApi.listAliases$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.listAliases{ result: Result<List<String>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.attested_secure_keys.AttestedSecureKeysApi.capabilities$separatedMessageChannelSuffix", codec, taskQueue)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.capabilities{ result: Result<PgCapabilities> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
