import { webcrypto } from 'node:crypto';

import {
  BasicConstraintsExtension,
  Extension,
  X509Certificate,
  X509CertificateGenerator,
} from '@peculiar/x509';
import * as asn1js from 'asn1js';

import type { Jwk, NormalizedAttestation, TrustStore } from '../../src/types.js';
import { GENUINE_CHALLENGE } from './genuine.js';

/**
 * Synthetic Android attestations, built and signed inside the test run.
 *
 * WHY THESE EXIST. A genuine bundle cannot be mutated into a negative for
 * anything inside the attestation extension: the leaf's signature covers it, so
 * flipping `origin` to IMPORTED makes the chain fail as *broken* long before
 * origin is read. Properties that live inside a signed structure can only be
 * varied by signing a new structure.
 *
 * WHAT THEY ARE AND ARE NOT. A synthetic key proves that a code path runs and
 * that a property is enforced. It proves nothing whatsoever about hardware —
 * the keys here are generated by Node, not by a keystore. Assertions about
 * hardware belong to the captured bundle in `genuine.ts`.
 *
 * The default parameters mirror the captured TEE bundle field for field, so each
 * negative differs from the synthetic positive in exactly one value — the same
 * one-difference discipline `mutate.ts` enforces for the JSON bundle.
 */

/** `SecurityLevel ::= ENUMERATED { Software(0), TrustedEnvironment(1), StrongBox(2) }` */
export const ATTESTATION_SECURITY_LEVEL = {
  software: 0,
  trustedEnvironment: 1,
  strongBox: 2,
} as const;

/** `KeyOrigin ::= INTEGER { GENERATED(0), DERIVED(1), IMPORTED(2), UNKNOWN(3) }` */
export const KEY_ORIGIN = {
  generated: 0,
  derived: 1,
  imported: 2,
  unknown: 3,
} as const;

/** `VerifiedBootState ::= ENUMERATED { Verified(0), SelfSigned(1), Unverified(2), Failed(3) }` */
export const VERIFIED_BOOT_STATE = {
  verified: 0,
  selfSigned: 1,
  unverified: 2,
  failed: 3,
} as const;

export interface RootOfTrustParams {
  deviceLocked: boolean;
  verifiedBootState: number;
}

/** The subset of an `AuthorizationList` these tests vary. */
export interface AuthorizationListParams {
  purpose?: number[];
  origin?: number;
  rootOfTrust?: RootOfTrustParams;
}

export interface KeyDescriptionParams {
  attestationSecurityLevel: number;
  keymasterSecurityLevel: number;
  challenge: Uint8Array;
  softwareEnforced: AuthorizationListParams;
  teeEnforced: AuthorizationListParams;
}

/** Mirrors the captured TEE bundle: KeyMint 4, TEE tier, generated, booted verified. */
export const GENUINE_SHAPED_KEY: KeyDescriptionParams = {
  attestationSecurityLevel: ATTESTATION_SECURITY_LEVEL.trustedEnvironment,
  keymasterSecurityLevel: ATTESTATION_SECURITY_LEVEL.trustedEnvironment,
  challenge: GENUINE_CHALLENGE,
  softwareEnforced: {},
  teeEnforced: {
    purpose: [2], // SIGN
    origin: KEY_ORIGIN.generated,
    rootOfTrust: {
      deviceLocked: true,
      verifiedBootState: VERIFIED_BOOT_STATE.verified,
    },
  },
};

export interface SyntheticAndroidKey {
  attestation: NormalizedAttestation;
  /** The attested key, as the client would claim it. */
  publicJwk: Jwk;
  /** A trust store pinning the synthetic root, so the chain anchors. */
  trust: TrustStore;
  /** Serial numbers of the chain, leaf first — the handle a revocation list uses. */
  serialNumbers: string[];
}

const crypto = webcrypto as unknown as Crypto;

const ANDROID_KEY_ATTESTATION_OID = '1.3.6.1.4.1.11129.2.1.17';

/** A window wide enough that no test needs to think about validity. */
const WIDE_WINDOW = { from: new Date('2020-01-01'), to: new Date('2040-01-01') };

/**
 * A leaf carrying a crafted `KeyDescription`, signed by a CA the returned trust
 * store pins. Override only the parameter under test.
 */
export async function syntheticAndroidKey(
  overrides: Partial<KeyDescriptionParams> = {},
  leafSerialNumber = '02',
): Promise<SyntheticAndroidKey> {
  const params: KeyDescriptionParams = {
    ...GENUINE_SHAPED_KEY,
    ...overrides,
    softwareEnforced: {
      ...GENUINE_SHAPED_KEY.softwareEnforced,
      ...overrides.softwareEnforced,
    },
    teeEnforced: {
      ...GENUINE_SHAPED_KEY.teeEnforced,
      ...overrides.teeEnforced,
    },
  };

  const root = await generateCa('CN=Synthetic Attestation Root', 'P-256', WIDE_WINDOW);
  const leaf = await issueLeaf(root, {
    namedCurve: 'P-256',
    window: WIDE_WINDOW,
    serialNumber: leafSerialNumber,
    extensions: [
      new Extension(
        ANDROID_KEY_ATTESTATION_OID,
        false,
        encodeKeyDescription(params),
      ),
    ],
  });

  return {
    attestation: {
      type: 'android-key',
      encoding: 'x5c-der',
      x5c: [leaf.cert, root.cert].map(derBase64),
      nonce: '',
    },
    publicJwk: leaf.publicJwk,
    trust: { googleRootsPem: [root.pem], appleRootPem: '' },
    serialNumbers: [leaf.cert.serialNumber, root.cert.serialNumber],
  };
}

/**
 * Encode a `KeyDescription` (RFC-less; the schema lives in Android's
 * `keymint/KeyMintDefs`). Tagged authorization entries are EXPLICIT context
 * tags, which is why each one wraps its value in a constructed block.
 */
export function encodeKeyDescription(params: KeyDescriptionParams): ArrayBuffer {
  return new asn1js.Sequence({
    value: [
      new asn1js.Integer({ value: 3 }), // attestationVersion
      new asn1js.Enumerated({ value: params.attestationSecurityLevel }),
      new asn1js.Integer({ value: 4 }), // keymasterVersion
      new asn1js.Enumerated({ value: params.keymasterSecurityLevel }),
      new asn1js.OctetString({ valueHex: toArrayBuffer(params.challenge) }),
      new asn1js.OctetString({ valueHex: new ArrayBuffer(0) }), // uniqueId
      authorizationList(params.softwareEnforced),
      authorizationList(params.teeEnforced),
    ],
  }).toBER(false);
}

function authorizationList(params: AuthorizationListParams): asn1js.Sequence {
  const entries: asn1js.BaseBlock[] = [];
  if (params.purpose) {
    entries.push(
      explicit(
        1,
        new asn1js.Set({
          value: params.purpose.map((p) => new asn1js.Integer({ value: p })),
        }),
      ),
    );
  }
  if (params.origin !== undefined) {
    entries.push(explicit(702, new asn1js.Integer({ value: params.origin })));
  }
  if (params.rootOfTrust) {
    entries.push(
      explicit(
        704,
        new asn1js.Sequence({
          value: [
            new asn1js.OctetString({ valueHex: new ArrayBuffer(32) }), // verifiedBootKey
            new asn1js.Boolean({ value: params.rootOfTrust.deviceLocked }),
            new asn1js.Enumerated({ value: params.rootOfTrust.verifiedBootState }),
            new asn1js.OctetString({ valueHex: new ArrayBuffer(32) }), // verifiedBootHash
          ],
        }),
      ),
    );
  }
  return new asn1js.Sequence({ value: entries });
}

function explicit(tagNumber: number, value: asn1js.BaseBlock): asn1js.BaseBlock {
  return new asn1js.Constructed({
    idBlock: { tagClass: 3, tagNumber },
    value: [value],
  });
}

// --- Certificate machinery -------------------------------------------------

export interface GeneratedCa {
  cert: X509Certificate;
  keys: webcrypto.CryptoKeyPair;
  /** The anchor as a caller would pin it. */
  pem: string;
}

/**
 * A throwaway self-signed CA. Generated per test run rather than committed, so
 * it can never be mistaken for captured evidence — and so tests about *now* can
 * put their validity window either side of the current instant without ever
 * depending on the calendar.
 */
export async function generateCa(
  name: string,
  namedCurve: 'P-256' | 'P-384',
  window: { from: Date; to: Date },
): Promise<GeneratedCa> {
  const keys = await generateEcKeyPair(namedCurve);
  const cert = await X509CertificateGenerator.createSelfSigned(
    {
      serialNumber: '01',
      name,
      notBefore: window.from,
      notAfter: window.to,
      signingAlgorithm: signingAlgorithmFor(namedCurve),
      keys,
      extensions: [new BasicConstraintsExtension(true, 2, true)],
    },
    crypto,
  );
  return { cert, keys, pem: cert.toString('pem') };
}

export interface IssuedLeaf {
  cert: X509Certificate;
  publicJwk: Jwk;
}

/** An end-entity certificate issued by `issuer` — a stand-in for a device leaf. */
export async function issueLeaf(
  issuer: GeneratedCa,
  options: {
    namedCurve: 'P-256' | 'P-384';
    window: { from: Date; to: Date };
    serialNumber?: string;
    extensions?: Extension[];
  },
): Promise<IssuedLeaf> {
  const keys = await generateEcKeyPair('P-256');
  const cert = await X509CertificateGenerator.create(
    {
      serialNumber: options.serialNumber ?? '02',
      subject: 'CN=Synthetic Leaf',
      issuer: issuer.cert.subject,
      notBefore: options.window.from,
      notAfter: options.window.to,
      signingAlgorithm: signingAlgorithmFor(options.namedCurve),
      signingKey: issuer.keys.privateKey,
      publicKey: keys.publicKey,
      extensions: options.extensions,
    },
    crypto,
  );
  return { cert, publicJwk: await exportJwk(keys.publicKey) };
}

export function derBase64(cert: X509Certificate | string): string {
  const parsed = typeof cert === 'string' ? new X509Certificate(cert) : cert;
  return Buffer.from(parsed.rawData).toString('base64');
}

async function generateEcKeyPair(
  namedCurve: 'P-256' | 'P-384',
): Promise<webcrypto.CryptoKeyPair> {
  return (await crypto.subtle.generateKey({ name: 'ECDSA', namedCurve }, true, [
    'sign',
    'verify',
  ])) as webcrypto.CryptoKeyPair;
}

async function exportJwk(key: CryptoKey): Promise<Jwk> {
  const jwk = (await crypto.subtle.exportKey('jwk', key)) as {
    kty?: string;
    crv?: string;
    x?: string;
    y?: string;
  };
  return {
    kty: jwk.kty ?? 'EC',
    crv: jwk.crv ?? 'P-256',
    x: jwk.x ?? '',
    y: jwk.y ?? '',
    alg: 'ES256',
  };
}

function signingAlgorithmFor(
  namedCurve: 'P-256' | 'P-384',
): webcrypto.EcdsaParams {
  return {
    name: 'ECDSA',
    hash: { name: namedCurve === 'P-384' ? 'SHA-384' : 'SHA-256' },
  };
}

function toArrayBuffer(bytes: Uint8Array): ArrayBuffer {
  return bytes.buffer.slice(
    bytes.byteOffset,
    bytes.byteOffset + bytes.byteLength,
  ) as ArrayBuffer;
}
