// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Where the private key material lives. Higher == stronger assurance.
enum PgSecurityLevel: Int, CaseIterable {
  case strongBox = 0
  case trustedEnvironment = 1
  case secureEnclave = 2
  case software = 3
  case unknown = 4
}

/// What proof of hardware origin the platform can produce for a key.
enum PgAttestationType: Int, CaseIterable {
  case androidKeyAttestation = 0
  case appleAppAttest = 1
  case none = 2
}

/// User-presence/verification requirement enforced by the OS on key use.
enum PgUserAuthType: Int, CaseIterable {
  case none = 0
  case deviceCredential = 1
  case biometricStrong = 2
  case biometricOrCredential = 3
}

/// Encoding of the verbatim attestation artifact handed to the server.
enum PgAttestationEncoding: Int, CaseIterable {
  case x5cDer = 0
  case cbor = 1
  case jwt = 2
}

/// iOS keychain accessibility for the persisted (encrypted) key blob.
enum PgIosAccessibility: Int, CaseIterable {
  case whenUnlockedThisDeviceOnly = 0
  case afterFirstUnlockThisDeviceOnly = 1
}

/// EC P-256 public key in JWK form (RFC 7517). `x`/`y` are base64url, unpadded.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PgJwk: Hashable, CustomStringConvertible {
  var kty: String
  var crv: String
  var x: String
  var y: String
  var alg: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PgJwk? {
    let kty = pigeonVar_list[0] as! String
    let crv = pigeonVar_list[1] as! String
    let x = pigeonVar_list[2] as! String
    let y = pigeonVar_list[3] as! String
    let alg = pigeonVar_list[4] as! String

    return PgJwk(
      kty: kty,
      crv: crv,
      x: x,
      y: y,
      alg: alg
    )
  }
  func toList() -> [Any?] {
    return [
      kty,
      crv,
      x,
      y,
      alg,
    ]
  }
  static func == (lhs: PgJwk, rhs: PgJwk) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.kty, rhs.kty) && MessagesPigeonInternal.deepEquals(lhs.crv, rhs.crv) && MessagesPigeonInternal.deepEquals(lhs.x, rhs.x) && MessagesPigeonInternal.deepEquals(lhs.y, rhs.y) && MessagesPigeonInternal.deepEquals(lhs.alg, rhs.alg)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PgJwk")
    MessagesPigeonInternal.deepHash(value: kty, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: crv, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: x, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: y, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: alg, hasher: &hasher)
  }

  public var description: String {
    return "PgJwk(kty: \(String(describing: kty)), crv: \(String(describing: crv)), x: \(String(describing: x)), y: \(String(describing: y)), alg: \(String(describing: alg)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PgUserAuthPolicy: Hashable, CustomStringConvertible {
  var type: PgUserAuthType
  /// 0 => per-use authentication (re-auth on every signature).
  var validityMillis: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PgUserAuthPolicy? {
    let type = pigeonVar_list[0] as! PgUserAuthType
    let validityMillis = pigeonVar_list[1] as! Int64

    return PgUserAuthPolicy(
      type: type,
      validityMillis: validityMillis
    )
  }
  func toList() -> [Any?] {
    return [
      type,
      validityMillis,
    ]
  }
  static func == (lhs: PgUserAuthPolicy, rhs: PgUserAuthPolicy) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.type, rhs.type) && MessagesPigeonInternal.deepEquals(lhs.validityMillis, rhs.validityMillis)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PgUserAuthPolicy")
    MessagesPigeonInternal.deepHash(value: type, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: validityMillis, hasher: &hasher)
  }

  public var description: String {
    return "PgUserAuthPolicy(type: \(String(describing: type)), validityMillis: \(String(describing: validityMillis)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PgAndroidKeyOptions: Hashable, CustomStringConvertible {
  var strongBoxPreferred: Bool
  var requireStrongBox: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PgAndroidKeyOptions? {
    let strongBoxPreferred = pigeonVar_list[0] as! Bool
    let requireStrongBox = pigeonVar_list[1] as! Bool

    return PgAndroidKeyOptions(
      strongBoxPreferred: strongBoxPreferred,
      requireStrongBox: requireStrongBox
    )
  }
  func toList() -> [Any?] {
    return [
      strongBoxPreferred,
      requireStrongBox,
    ]
  }
  static func == (lhs: PgAndroidKeyOptions, rhs: PgAndroidKeyOptions) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.strongBoxPreferred, rhs.strongBoxPreferred) && MessagesPigeonInternal.deepEquals(lhs.requireStrongBox, rhs.requireStrongBox)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PgAndroidKeyOptions")
    MessagesPigeonInternal.deepHash(value: strongBoxPreferred, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: requireStrongBox, hasher: &hasher)
  }

  public var description: String {
    return "PgAndroidKeyOptions(strongBoxPreferred: \(String(describing: strongBoxPreferred)), requireStrongBox: \(String(describing: requireStrongBox)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PgIosKeyOptions: Hashable, CustomStringConvertible {
  var accessibility: PgIosAccessibility
  var accessGroup: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PgIosKeyOptions? {
    let accessibility = pigeonVar_list[0] as! PgIosAccessibility
    let accessGroup: String? = nilOrValue(pigeonVar_list[1])

    return PgIosKeyOptions(
      accessibility: accessibility,
      accessGroup: accessGroup
    )
  }
  func toList() -> [Any?] {
    return [
      accessibility,
      accessGroup,
    ]
  }
  static func == (lhs: PgIosKeyOptions, rhs: PgIosKeyOptions) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.accessibility, rhs.accessibility) && MessagesPigeonInternal.deepEquals(lhs.accessGroup, rhs.accessGroup)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PgIosKeyOptions")
    MessagesPigeonInternal.deepHash(value: accessibility, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: accessGroup, hasher: &hasher)
  }

  public var description: String {
    return "PgIosKeyOptions(accessibility: \(String(describing: accessibility)), accessGroup: \(String(describing: accessGroup)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PgGenerateKeyRequest: Hashable, CustomStringConvertible {
  var alias: String
  var minSecurityLevel: PgSecurityLevel
  var userAuth: PgUserAuthPolicy
  var android: PgAndroidKeyOptions
  var ios: PgIosKeyOptions


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PgGenerateKeyRequest? {
    let alias = pigeonVar_list[0] as! String
    let minSecurityLevel = pigeonVar_list[1] as! PgSecurityLevel
    let userAuth = pigeonVar_list[2] as! PgUserAuthPolicy
    let android = pigeonVar_list[3] as! PgAndroidKeyOptions
    let ios = pigeonVar_list[4] as! PgIosKeyOptions

    return PgGenerateKeyRequest(
      alias: alias,
      minSecurityLevel: minSecurityLevel,
      userAuth: userAuth,
      android: android,
      ios: ios
    )
  }
  func toList() -> [Any?] {
    return [
      alias,
      minSecurityLevel,
      userAuth,
      android,
      ios,
    ]
  }
  static func == (lhs: PgGenerateKeyRequest, rhs: PgGenerateKeyRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.alias, rhs.alias) && MessagesPigeonInternal.deepEquals(lhs.minSecurityLevel, rhs.minSecurityLevel) && MessagesPigeonInternal.deepEquals(lhs.userAuth, rhs.userAuth) && MessagesPigeonInternal.deepEquals(lhs.android, rhs.android) && MessagesPigeonInternal.deepEquals(lhs.ios, rhs.ios)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PgGenerateKeyRequest")
    MessagesPigeonInternal.deepHash(value: alias, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: minSecurityLevel, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: userAuth, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: android, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: ios, hasher: &hasher)
  }

  public var description: String {
    return "PgGenerateKeyRequest(alias: \(String(describing: alias)), minSecurityLevel: \(String(describing: minSecurityLevel)), userAuth: \(String(describing: userAuth)), android: \(String(describing: android)), ios: \(String(describing: ios)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PgGeneratedKey: Hashable, CustomStringConvertible {
  var alias: String
  var publicJwk: PgJwk
  var requestedLevel: PgSecurityLevel
  var effectiveLevel: PgSecurityLevel
  var attestationType: PgAttestationType
  var gatedByUserAuth: Bool
  var userAuthType: PgUserAuthType


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PgGeneratedKey? {
    let alias = pigeonVar_list[0] as! String
    let publicJwk = pigeonVar_list[1] as! PgJwk
    let requestedLevel = pigeonVar_list[2] as! PgSecurityLevel
    let effectiveLevel = pigeonVar_list[3] as! PgSecurityLevel
    let attestationType = pigeonVar_list[4] as! PgAttestationType
    let gatedByUserAuth = pigeonVar_list[5] as! Bool
    let userAuthType = pigeonVar_list[6] as! PgUserAuthType

    return PgGeneratedKey(
      alias: alias,
      publicJwk: publicJwk,
      requestedLevel: requestedLevel,
      effectiveLevel: effectiveLevel,
      attestationType: attestationType,
      gatedByUserAuth: gatedByUserAuth,
      userAuthType: userAuthType
    )
  }
  func toList() -> [Any?] {
    return [
      alias,
      publicJwk,
      requestedLevel,
      effectiveLevel,
      attestationType,
      gatedByUserAuth,
      userAuthType,
    ]
  }
  static func == (lhs: PgGeneratedKey, rhs: PgGeneratedKey) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.alias, rhs.alias) && MessagesPigeonInternal.deepEquals(lhs.publicJwk, rhs.publicJwk) && MessagesPigeonInternal.deepEquals(lhs.requestedLevel, rhs.requestedLevel) && MessagesPigeonInternal.deepEquals(lhs.effectiveLevel, rhs.effectiveLevel) && MessagesPigeonInternal.deepEquals(lhs.attestationType, rhs.attestationType) && MessagesPigeonInternal.deepEquals(lhs.gatedByUserAuth, rhs.gatedByUserAuth) && MessagesPigeonInternal.deepEquals(lhs.userAuthType, rhs.userAuthType)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PgGeneratedKey")
    MessagesPigeonInternal.deepHash(value: alias, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: publicJwk, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: requestedLevel, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: effectiveLevel, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: attestationType, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: gatedByUserAuth, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: userAuthType, hasher: &hasher)
  }

  public var description: String {
    return "PgGeneratedKey(alias: \(String(describing: alias)), publicJwk: \(String(describing: publicJwk)), requestedLevel: \(String(describing: requestedLevel)), effectiveLevel: \(String(describing: effectiveLevel)), attestationType: \(String(describing: attestationType)), gatedByUserAuth: \(String(describing: gatedByUserAuth)), userAuthType: \(String(describing: userAuthType)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PgSignRequest: Hashable, CustomStringConvertible {
  var alias: String
  var payload: FlutterStandardTypedData
  var promptTitle: String? = nil
  var promptSubtitle: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PgSignRequest? {
    let alias = pigeonVar_list[0] as! String
    let payload = pigeonVar_list[1] as! FlutterStandardTypedData
    let promptTitle: String? = nilOrValue(pigeonVar_list[2])
    let promptSubtitle: String? = nilOrValue(pigeonVar_list[3])

    return PgSignRequest(
      alias: alias,
      payload: payload,
      promptTitle: promptTitle,
      promptSubtitle: promptSubtitle
    )
  }
  func toList() -> [Any?] {
    return [
      alias,
      payload,
      promptTitle,
      promptSubtitle,
    ]
  }
  static func == (lhs: PgSignRequest, rhs: PgSignRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.alias, rhs.alias) && MessagesPigeonInternal.deepEquals(lhs.payload, rhs.payload) && MessagesPigeonInternal.deepEquals(lhs.promptTitle, rhs.promptTitle) && MessagesPigeonInternal.deepEquals(lhs.promptSubtitle, rhs.promptSubtitle)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PgSignRequest")
    MessagesPigeonInternal.deepHash(value: alias, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: payload, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: promptTitle, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: promptSubtitle, hasher: &hasher)
  }

  public var description: String {
    return "PgSignRequest(alias: \(String(describing: alias)), payload: \(String(describing: payload)), promptTitle: \(String(describing: promptTitle)), promptSubtitle: \(String(describing: promptSubtitle)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PgSignature: Hashable, CustomStringConvertible {
  /// Raw `R||S`, exactly 64 bytes (JOSE/COSE form, not DER).
  var rawRS: FlutterStandardTypedData


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PgSignature? {
    let rawRS = pigeonVar_list[0] as! FlutterStandardTypedData

    return PgSignature(
      rawRS: rawRS
    )
  }
  func toList() -> [Any?] {
    return [
      rawRS
    ]
  }
  static func == (lhs: PgSignature, rhs: PgSignature) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.rawRS, rhs.rawRS)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PgSignature")
    MessagesPigeonInternal.deepHash(value: rawRS, hasher: &hasher)
  }

  public var description: String {
    return "PgSignature(rawRS: \(String(describing: rawRS)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PgAttestRequest: Hashable, CustomStringConvertible {
  var alias: String
  var nonce: FlutterStandardTypedData


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PgAttestRequest? {
    let alias = pigeonVar_list[0] as! String
    let nonce = pigeonVar_list[1] as! FlutterStandardTypedData

    return PgAttestRequest(
      alias: alias,
      nonce: nonce
    )
  }
  func toList() -> [Any?] {
    return [
      alias,
      nonce,
    ]
  }
  static func == (lhs: PgAttestRequest, rhs: PgAttestRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.alias, rhs.alias) && MessagesPigeonInternal.deepEquals(lhs.nonce, rhs.nonce)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PgAttestRequest")
    MessagesPigeonInternal.deepHash(value: alias, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: nonce, hasher: &hasher)
  }

  public var description: String {
    return "PgAttestRequest(alias: \(String(describing: alias)), nonce: \(String(describing: nonce)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PgAttestation: Hashable, CustomStringConvertible {
  var type: PgAttestationType
  var encoding: PgAttestationEncoding
  /// Android: cert chain as base64 DER (leaf first). Apple: x5c if present.
  var x5c: [String]
  /// iOS App Attest CBOR object / assertion bytes; null on Android.
  var raw: FlutterStandardTypedData? = nil
  var attestedKey: PgJwk
  var nonce: FlutterStandardTypedData


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PgAttestation? {
    let type = pigeonVar_list[0] as! PgAttestationType
    let encoding = pigeonVar_list[1] as! PgAttestationEncoding
    let x5c = pigeonVar_list[2] as! [String]
    let raw: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[3])
    let attestedKey = pigeonVar_list[4] as! PgJwk
    let nonce = pigeonVar_list[5] as! FlutterStandardTypedData

    return PgAttestation(
      type: type,
      encoding: encoding,
      x5c: x5c,
      raw: raw,
      attestedKey: attestedKey,
      nonce: nonce
    )
  }
  func toList() -> [Any?] {
    return [
      type,
      encoding,
      x5c,
      raw,
      attestedKey,
      nonce,
    ]
  }
  static func == (lhs: PgAttestation, rhs: PgAttestation) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.type, rhs.type) && MessagesPigeonInternal.deepEquals(lhs.encoding, rhs.encoding) && MessagesPigeonInternal.deepEquals(lhs.x5c, rhs.x5c) && MessagesPigeonInternal.deepEquals(lhs.raw, rhs.raw) && MessagesPigeonInternal.deepEquals(lhs.attestedKey, rhs.attestedKey) && MessagesPigeonInternal.deepEquals(lhs.nonce, rhs.nonce)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PgAttestation")
    MessagesPigeonInternal.deepHash(value: type, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: encoding, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: x5c, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: raw, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: attestedKey, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: nonce, hasher: &hasher)
  }

  public var description: String {
    return "PgAttestation(type: \(String(describing: type)), encoding: \(String(describing: encoding)), x5c: \(String(describing: x5c)), raw: \(String(describing: raw)), attestedKey: \(String(describing: attestedKey)), nonce: \(String(describing: nonce)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PgKeyInfo: Hashable, CustomStringConvertible {
  var alias: String
  var publicJwk: PgJwk
  var securityLevel: PgSecurityLevel
  var attestationType: PgAttestationType
  var gatedByUserAuth: Bool
  var userAuthType: PgUserAuthType


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PgKeyInfo? {
    let alias = pigeonVar_list[0] as! String
    let publicJwk = pigeonVar_list[1] as! PgJwk
    let securityLevel = pigeonVar_list[2] as! PgSecurityLevel
    let attestationType = pigeonVar_list[3] as! PgAttestationType
    let gatedByUserAuth = pigeonVar_list[4] as! Bool
    let userAuthType = pigeonVar_list[5] as! PgUserAuthType

    return PgKeyInfo(
      alias: alias,
      publicJwk: publicJwk,
      securityLevel: securityLevel,
      attestationType: attestationType,
      gatedByUserAuth: gatedByUserAuth,
      userAuthType: userAuthType
    )
  }
  func toList() -> [Any?] {
    return [
      alias,
      publicJwk,
      securityLevel,
      attestationType,
      gatedByUserAuth,
      userAuthType,
    ]
  }
  static func == (lhs: PgKeyInfo, rhs: PgKeyInfo) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.alias, rhs.alias) && MessagesPigeonInternal.deepEquals(lhs.publicJwk, rhs.publicJwk) && MessagesPigeonInternal.deepEquals(lhs.securityLevel, rhs.securityLevel) && MessagesPigeonInternal.deepEquals(lhs.attestationType, rhs.attestationType) && MessagesPigeonInternal.deepEquals(lhs.gatedByUserAuth, rhs.gatedByUserAuth) && MessagesPigeonInternal.deepEquals(lhs.userAuthType, rhs.userAuthType)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PgKeyInfo")
    MessagesPigeonInternal.deepHash(value: alias, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: publicJwk, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: securityLevel, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: attestationType, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: gatedByUserAuth, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: userAuthType, hasher: &hasher)
  }

  public var description: String {
    return "PgKeyInfo(alias: \(String(describing: alias)), publicJwk: \(String(describing: publicJwk)), securityLevel: \(String(describing: securityLevel)), attestationType: \(String(describing: attestationType)), gatedByUserAuth: \(String(describing: gatedByUserAuth)), userAuthType: \(String(describing: userAuthType)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PgCapabilities: Hashable, CustomStringConvertible {
  var hasStrongBox: Bool
  var hasTee: Bool
  var hasSecureEnclave: Bool
  var supportsKeyAttestation: Bool
  var supportsBiometricGating: Bool
  var bestAvailableLevel: PgSecurityLevel
  var androidApiLevel: Int64? = nil
  var iosVersion: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PgCapabilities? {
    let hasStrongBox = pigeonVar_list[0] as! Bool
    let hasTee = pigeonVar_list[1] as! Bool
    let hasSecureEnclave = pigeonVar_list[2] as! Bool
    let supportsKeyAttestation = pigeonVar_list[3] as! Bool
    let supportsBiometricGating = pigeonVar_list[4] as! Bool
    let bestAvailableLevel = pigeonVar_list[5] as! PgSecurityLevel
    let androidApiLevel: Int64? = nilOrValue(pigeonVar_list[6])
    let iosVersion: String? = nilOrValue(pigeonVar_list[7])

    return PgCapabilities(
      hasStrongBox: hasStrongBox,
      hasTee: hasTee,
      hasSecureEnclave: hasSecureEnclave,
      supportsKeyAttestation: supportsKeyAttestation,
      supportsBiometricGating: supportsBiometricGating,
      bestAvailableLevel: bestAvailableLevel,
      androidApiLevel: androidApiLevel,
      iosVersion: iosVersion
    )
  }
  func toList() -> [Any?] {
    return [
      hasStrongBox,
      hasTee,
      hasSecureEnclave,
      supportsKeyAttestation,
      supportsBiometricGating,
      bestAvailableLevel,
      androidApiLevel,
      iosVersion,
    ]
  }
  static func == (lhs: PgCapabilities, rhs: PgCapabilities) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.hasStrongBox, rhs.hasStrongBox) && MessagesPigeonInternal.deepEquals(lhs.hasTee, rhs.hasTee) && MessagesPigeonInternal.deepEquals(lhs.hasSecureEnclave, rhs.hasSecureEnclave) && MessagesPigeonInternal.deepEquals(lhs.supportsKeyAttestation, rhs.supportsKeyAttestation) && MessagesPigeonInternal.deepEquals(lhs.supportsBiometricGating, rhs.supportsBiometricGating) && MessagesPigeonInternal.deepEquals(lhs.bestAvailableLevel, rhs.bestAvailableLevel) && MessagesPigeonInternal.deepEquals(lhs.androidApiLevel, rhs.androidApiLevel) && MessagesPigeonInternal.deepEquals(lhs.iosVersion, rhs.iosVersion)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PgCapabilities")
    MessagesPigeonInternal.deepHash(value: hasStrongBox, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: hasTee, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: hasSecureEnclave, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: supportsKeyAttestation, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: supportsBiometricGating, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: bestAvailableLevel, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: androidApiLevel, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: iosVersion, hasher: &hasher)
  }

  public var description: String {
    return "PgCapabilities(hasStrongBox: \(String(describing: hasStrongBox)), hasTee: \(String(describing: hasTee)), hasSecureEnclave: \(String(describing: hasSecureEnclave)), supportsKeyAttestation: \(String(describing: supportsKeyAttestation)), supportsBiometricGating: \(String(describing: supportsBiometricGating)), bestAvailableLevel: \(String(describing: bestAvailableLevel)), androidApiLevel: \(String(describing: androidApiLevel)), iosVersion: \(String(describing: iosVersion)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PgSecurityLevel(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PgAttestationType(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PgUserAuthType(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PgAttestationEncoding(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PgIosAccessibility(rawValue: enumResultAsInt)
      }
      return nil
    case 134:
      return PgJwk.fromList(self.readValue() as! [Any?])
    case 135:
      return PgUserAuthPolicy.fromList(self.readValue() as! [Any?])
    case 136:
      return PgAndroidKeyOptions.fromList(self.readValue() as! [Any?])
    case 137:
      return PgIosKeyOptions.fromList(self.readValue() as! [Any?])
    case 138:
      return PgGenerateKeyRequest.fromList(self.readValue() as! [Any?])
    case 139:
      return PgGeneratedKey.fromList(self.readValue() as! [Any?])
    case 140:
      return PgSignRequest.fromList(self.readValue() as! [Any?])
    case 141:
      return PgSignature.fromList(self.readValue() as! [Any?])
    case 142:
      return PgAttestRequest.fromList(self.readValue() as! [Any?])
    case 143:
      return PgAttestation.fromList(self.readValue() as! [Any?])
    case 144:
      return PgKeyInfo.fromList(self.readValue() as! [Any?])
    case 145:
      return PgCapabilities.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? PgSecurityLevel {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? PgAttestationType {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? PgUserAuthType {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? PgAttestationEncoding {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? PgIosAccessibility {
      super.writeByte(133)
      super.writeValue(value.rawValue)
    } else if let value = value as? PgJwk {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? PgUserAuthPolicy {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? PgAndroidKeyOptions {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? PgIosKeyOptions {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? PgGenerateKeyRequest {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? PgGeneratedKey {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? PgSignRequest {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else if let value = value as? PgSignature {
      super.writeByte(141)
      super.writeValue(value.toList())
    } else if let value = value as? PgAttestRequest {
      super.writeByte(142)
      super.writeValue(value.toList())
    } else if let value = value as? PgAttestation {
      super.writeByte(143)
      super.writeValue(value.toList())
    } else if let value = value as? PgKeyInfo {
      super.writeByte(144)
      super.writeValue(value.toList())
    } else if let value = value as? PgCapabilities {
      super.writeByte(145)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol AttestedSecureKeysApi {
  /// Generate a NEW non-exportable EC P-256 key in the strongest available
  /// secure hardware. Throws (FlutterError code `unsupported_security_level`)
  /// if [PgGenerateKeyRequest.minSecurityLevel] cannot be met.
  func generateKey(request: PgGenerateKeyRequest, completion: @escaping (Result<PgGeneratedKey, Error>) -> Void)
  /// ES256-sign the payload, returning raw 64-byte `R||S`.
  /// Triggers the OS biometric/PIN prompt when the key is auth-gated.
  func sign(request: PgSignRequest, completion: @escaping (Result<PgSignature, Error>) -> Void)
  /// Produce a fresh attestation bound to the supplied server nonce.
  func attest(request: PgAttestRequest, completion: @escaping (Result<PgAttestation, Error>) -> Void)
  func getKeyInfo(alias: String, completion: @escaping (Result<PgKeyInfo?, Error>) -> Void)
  func containsKey(alias: String) throws -> Bool
  func deleteKey(alias: String, completion: @escaping (Result<Void, Error>) -> Void)
  func listAliases(completion: @escaping (Result<[String], Error>) -> Void)
  /// Probe what this device/OS can actually do, before generating anything.
  func capabilities(completion: @escaping (Result<PgCapabilities, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class AttestedSecureKeysApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `AttestedSecureKeysApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: AttestedSecureKeysApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Generate a NEW non-exportable EC P-256 key in the strongest available
    /// secure hardware. Throws (FlutterError code `unsupported_security_level`)
    /// if [PgGenerateKeyRequest.minSecurityLevel] cannot be met.
    let generateKeyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.attested_secure_keys.AttestedSecureKeysApi.generateKey\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      generateKeyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! PgGenerateKeyRequest
        api.generateKey(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      generateKeyChannel.setMessageHandler(nil)
    }
    /// ES256-sign the payload, returning raw 64-byte `R||S`.
    /// Triggers the OS biometric/PIN prompt when the key is auth-gated.
    let signChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.attested_secure_keys.AttestedSecureKeysApi.sign\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      signChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! PgSignRequest
        api.sign(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      signChannel.setMessageHandler(nil)
    }
    /// Produce a fresh attestation bound to the supplied server nonce.
    let attestChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.attested_secure_keys.AttestedSecureKeysApi.attest\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      attestChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! PgAttestRequest
        api.attest(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      attestChannel.setMessageHandler(nil)
    }
    let getKeyInfoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.attested_secure_keys.AttestedSecureKeysApi.getKeyInfo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getKeyInfoChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let aliasArg = args[0] as! String
        api.getKeyInfo(alias: aliasArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getKeyInfoChannel.setMessageHandler(nil)
    }
    let containsKeyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.attested_secure_keys.AttestedSecureKeysApi.containsKey\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      containsKeyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let aliasArg = args[0] as! String
        do {
          let result = try api.containsKey(alias: aliasArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      containsKeyChannel.setMessageHandler(nil)
    }
    let deleteKeyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.attested_secure_keys.AttestedSecureKeysApi.deleteKey\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      deleteKeyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let aliasArg = args[0] as! String
        api.deleteKey(alias: aliasArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      deleteKeyChannel.setMessageHandler(nil)
    }
    let listAliasesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.attested_secure_keys.AttestedSecureKeysApi.listAliases\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      listAliasesChannel.setMessageHandler { _, reply in
        api.listAliases { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      listAliasesChannel.setMessageHandler(nil)
    }
    /// Probe what this device/OS can actually do, before generating anything.
    let capabilitiesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.attested_secure_keys.AttestedSecureKeysApi.capabilities\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      capabilitiesChannel.setMessageHandler { _, reply in
        api.capabilities { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      capabilitiesChannel.setMessageHandler(nil)
    }
  }
}
