// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// Where the private key material lives. Higher == stronger assurance.
enum PgSecurityLevel {
  strongBox,
  trustedEnvironment,
  secureEnclave,
  software,
  unknown,
}

/// What proof of hardware origin the platform can produce for a key.
enum PgAttestationType {
  androidKeyAttestation,
  appleAppAttest,
  none,
}

/// User-presence/verification requirement enforced by the OS on key use.
enum PgUserAuthType {
  none,
  deviceCredential,
  biometricStrong,
  biometricOrCredential,
}

/// Encoding of the verbatim attestation artifact handed to the server.
enum PgAttestationEncoding {
  x5cDer,
  cbor,
  jwt,
}

/// iOS keychain accessibility for the persisted (encrypted) key blob.
enum PgIosAccessibility {
  whenUnlockedThisDeviceOnly,
  afterFirstUnlockThisDeviceOnly,
}

/// EC P-256 public key in JWK form (RFC 7517). `x`/`y` are base64url, unpadded.
class PgJwk {
  PgJwk({
    required this.kty,
    required this.crv,
    required this.x,
    required this.y,
    required this.alg,
  });

  String kty;

  String crv;

  String x;

  String y;

  String alg;

  List<Object?> _toList() {
    return <Object?>[
      kty,
      crv,
      x,
      y,
      alg,
    ];
  }

  Object encode() {
    return _toList();  }

  static PgJwk decode(Object result) {
    result as List<Object?>;
    return PgJwk(
      kty: result[0]! as String,
      crv: result[1]! as String,
      x: result[2]! as String,
      y: result[3]! as String,
      alg: result[4]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PgJwk || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(kty, other.kty) && _deepEquals(crv, other.crv) && _deepEquals(x, other.x) && _deepEquals(y, other.y) && _deepEquals(alg, other.alg);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PgJwk(kty: $kty, crv: $crv, x: $x, y: $y, alg: $alg)';
  }
}

class PgUserAuthPolicy {
  PgUserAuthPolicy({
    required this.type,
    required this.validityMillis,
  });

  PgUserAuthType type;

  /// 0 => per-use authentication (re-auth on every signature).
  int validityMillis;

  List<Object?> _toList() {
    return <Object?>[
      type,
      validityMillis,
    ];
  }

  Object encode() {
    return _toList();  }

  static PgUserAuthPolicy decode(Object result) {
    result as List<Object?>;
    return PgUserAuthPolicy(
      type: result[0]! as PgUserAuthType,
      validityMillis: result[1]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PgUserAuthPolicy || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(type, other.type) && _deepEquals(validityMillis, other.validityMillis);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PgUserAuthPolicy(type: $type, validityMillis: $validityMillis)';
  }
}

class PgAndroidKeyOptions {
  PgAndroidKeyOptions({
    required this.strongBoxPreferred,
    required this.requireStrongBox,
  });

  bool strongBoxPreferred;

  bool requireStrongBox;

  List<Object?> _toList() {
    return <Object?>[
      strongBoxPreferred,
      requireStrongBox,
    ];
  }

  Object encode() {
    return _toList();  }

  static PgAndroidKeyOptions decode(Object result) {
    result as List<Object?>;
    return PgAndroidKeyOptions(
      strongBoxPreferred: result[0]! as bool,
      requireStrongBox: result[1]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PgAndroidKeyOptions || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(strongBoxPreferred, other.strongBoxPreferred) && _deepEquals(requireStrongBox, other.requireStrongBox);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PgAndroidKeyOptions(strongBoxPreferred: $strongBoxPreferred, requireStrongBox: $requireStrongBox)';
  }
}

class PgIosKeyOptions {
  PgIosKeyOptions({
    required this.accessibility,
    this.accessGroup,
  });

  PgIosAccessibility accessibility;

  String? accessGroup;

  List<Object?> _toList() {
    return <Object?>[
      accessibility,
      accessGroup,
    ];
  }

  Object encode() {
    return _toList();  }

  static PgIosKeyOptions decode(Object result) {
    result as List<Object?>;
    return PgIosKeyOptions(
      accessibility: result[0]! as PgIosAccessibility,
      accessGroup: result[1] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PgIosKeyOptions || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(accessibility, other.accessibility) && _deepEquals(accessGroup, other.accessGroup);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PgIosKeyOptions(accessibility: $accessibility, accessGroup: $accessGroup)';
  }
}

class PgGenerateKeyRequest {
  PgGenerateKeyRequest({
    required this.alias,
    required this.minSecurityLevel,
    required this.userAuth,
    required this.android,
    required this.ios,
    this.attestationChallenge,
  });

  String alias;

  PgSecurityLevel minSecurityLevel;

  PgUserAuthPolicy userAuth;

  PgAndroidKeyOptions android;

  PgIosKeyOptions ios;

  /// Optional server nonce to embed as the Android key-attestation challenge,
  /// bound at key-generation time (Android fixes the challenge at keygen). When
  /// null, Android falls back to the alias as a placeholder. iOS ignores this —
  /// App Attest binds the nonce later, in [AttestedSecureKeysApi.attest].
  Uint8List? attestationChallenge;

  List<Object?> _toList() {
    return <Object?>[
      alias,
      minSecurityLevel,
      userAuth,
      android,
      ios,
      attestationChallenge,
    ];
  }

  Object encode() {
    return _toList();  }

  static PgGenerateKeyRequest decode(Object result) {
    result as List<Object?>;
    return PgGenerateKeyRequest(
      alias: result[0]! as String,
      minSecurityLevel: result[1]! as PgSecurityLevel,
      userAuth: result[2]! as PgUserAuthPolicy,
      android: result[3]! as PgAndroidKeyOptions,
      ios: result[4]! as PgIosKeyOptions,
      attestationChallenge: result[5] as Uint8List?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PgGenerateKeyRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(alias, other.alias) && _deepEquals(minSecurityLevel, other.minSecurityLevel) && _deepEquals(userAuth, other.userAuth) && _deepEquals(android, other.android) && _deepEquals(ios, other.ios) && _deepEquals(attestationChallenge, other.attestationChallenge);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PgGenerateKeyRequest(alias: $alias, minSecurityLevel: $minSecurityLevel, userAuth: $userAuth, android: $android, ios: $ios, attestationChallenge: $attestationChallenge)';
  }
}

class PgGeneratedKey {
  PgGeneratedKey({
    required this.alias,
    required this.publicJwk,
    required this.requestedLevel,
    required this.effectiveLevel,
    required this.attestationType,
    required this.gatedByUserAuth,
    required this.userAuthType,
  });

  String alias;

  PgJwk publicJwk;

  PgSecurityLevel requestedLevel;

  PgSecurityLevel effectiveLevel;

  PgAttestationType attestationType;

  bool gatedByUserAuth;

  PgUserAuthType userAuthType;

  List<Object?> _toList() {
    return <Object?>[
      alias,
      publicJwk,
      requestedLevel,
      effectiveLevel,
      attestationType,
      gatedByUserAuth,
      userAuthType,
    ];
  }

  Object encode() {
    return _toList();  }

  static PgGeneratedKey decode(Object result) {
    result as List<Object?>;
    return PgGeneratedKey(
      alias: result[0]! as String,
      publicJwk: result[1]! as PgJwk,
      requestedLevel: result[2]! as PgSecurityLevel,
      effectiveLevel: result[3]! as PgSecurityLevel,
      attestationType: result[4]! as PgAttestationType,
      gatedByUserAuth: result[5]! as bool,
      userAuthType: result[6]! as PgUserAuthType,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PgGeneratedKey || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(alias, other.alias) && _deepEquals(publicJwk, other.publicJwk) && _deepEquals(requestedLevel, other.requestedLevel) && _deepEquals(effectiveLevel, other.effectiveLevel) && _deepEquals(attestationType, other.attestationType) && _deepEquals(gatedByUserAuth, other.gatedByUserAuth) && _deepEquals(userAuthType, other.userAuthType);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PgGeneratedKey(alias: $alias, publicJwk: $publicJwk, requestedLevel: $requestedLevel, effectiveLevel: $effectiveLevel, attestationType: $attestationType, gatedByUserAuth: $gatedByUserAuth, userAuthType: $userAuthType)';
  }
}

class PgSignRequest {
  PgSignRequest({
    required this.alias,
    required this.payload,
    this.promptTitle,
    this.promptSubtitle,
  });

  String alias;

  Uint8List payload;

  String? promptTitle;

  String? promptSubtitle;

  List<Object?> _toList() {
    return <Object?>[
      alias,
      payload,
      promptTitle,
      promptSubtitle,
    ];
  }

  Object encode() {
    return _toList();  }

  static PgSignRequest decode(Object result) {
    result as List<Object?>;
    return PgSignRequest(
      alias: result[0]! as String,
      payload: result[1]! as Uint8List,
      promptTitle: result[2] as String?,
      promptSubtitle: result[3] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PgSignRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(alias, other.alias) && _deepEquals(payload, other.payload) && _deepEquals(promptTitle, other.promptTitle) && _deepEquals(promptSubtitle, other.promptSubtitle);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PgSignRequest(alias: $alias, payload: $payload, promptTitle: $promptTitle, promptSubtitle: $promptSubtitle)';
  }
}

class PgSignature {
  PgSignature({
    required this.rawRS,
  });

  /// Raw `R||S`, exactly 64 bytes (JOSE/COSE form, not DER).
  Uint8List rawRS;

  List<Object?> _toList() {
    return <Object?>[
      rawRS,
    ];
  }

  Object encode() {
    return _toList();  }

  static PgSignature decode(Object result) {
    result as List<Object?>;
    return PgSignature(
      rawRS: result[0]! as Uint8List,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PgSignature || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(rawRS, other.rawRS);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PgSignature(rawRS: $rawRS)';
  }
}

class PgAttestRequest {
  PgAttestRequest({
    required this.alias,
    required this.nonce,
  });

  String alias;

  Uint8List nonce;

  List<Object?> _toList() {
    return <Object?>[
      alias,
      nonce,
    ];
  }

  Object encode() {
    return _toList();  }

  static PgAttestRequest decode(Object result) {
    result as List<Object?>;
    return PgAttestRequest(
      alias: result[0]! as String,
      nonce: result[1]! as Uint8List,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PgAttestRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(alias, other.alias) && _deepEquals(nonce, other.nonce);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PgAttestRequest(alias: $alias, nonce: $nonce)';
  }
}

class PgAttestation {
  PgAttestation({
    required this.type,
    required this.encoding,
    required this.x5c,
    this.raw,
    required this.attestedKey,
    required this.nonce,
  });

  PgAttestationType type;

  PgAttestationEncoding encoding;

  /// Android: cert chain as base64 DER (leaf first). Apple: x5c if present.
  List<String> x5c;

  /// iOS App Attest CBOR object / assertion bytes; null on Android.
  Uint8List? raw;

  PgJwk attestedKey;

  Uint8List nonce;

  List<Object?> _toList() {
    return <Object?>[
      type,
      encoding,
      x5c,
      raw,
      attestedKey,
      nonce,
    ];
  }

  Object encode() {
    return _toList();  }

  static PgAttestation decode(Object result) {
    result as List<Object?>;
    return PgAttestation(
      type: result[0]! as PgAttestationType,
      encoding: result[1]! as PgAttestationEncoding,
      x5c: (result[2]! as List<Object?>).cast<String>(),
      raw: result[3] as Uint8List?,
      attestedKey: result[4]! as PgJwk,
      nonce: result[5]! as Uint8List,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PgAttestation || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(type, other.type) && _deepEquals(encoding, other.encoding) && _deepEquals(x5c, other.x5c) && _deepEquals(raw, other.raw) && _deepEquals(attestedKey, other.attestedKey) && _deepEquals(nonce, other.nonce);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PgAttestation(type: $type, encoding: $encoding, x5c: $x5c, raw: $raw, attestedKey: $attestedKey, nonce: $nonce)';
  }
}

class PgKeyInfo {
  PgKeyInfo({
    required this.alias,
    required this.publicJwk,
    required this.securityLevel,
    required this.attestationType,
    required this.gatedByUserAuth,
    required this.userAuthType,
  });

  String alias;

  PgJwk publicJwk;

  PgSecurityLevel securityLevel;

  PgAttestationType attestationType;

  bool gatedByUserAuth;

  PgUserAuthType userAuthType;

  List<Object?> _toList() {
    return <Object?>[
      alias,
      publicJwk,
      securityLevel,
      attestationType,
      gatedByUserAuth,
      userAuthType,
    ];
  }

  Object encode() {
    return _toList();  }

  static PgKeyInfo decode(Object result) {
    result as List<Object?>;
    return PgKeyInfo(
      alias: result[0]! as String,
      publicJwk: result[1]! as PgJwk,
      securityLevel: result[2]! as PgSecurityLevel,
      attestationType: result[3]! as PgAttestationType,
      gatedByUserAuth: result[4]! as bool,
      userAuthType: result[5]! as PgUserAuthType,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PgKeyInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(alias, other.alias) && _deepEquals(publicJwk, other.publicJwk) && _deepEquals(securityLevel, other.securityLevel) && _deepEquals(attestationType, other.attestationType) && _deepEquals(gatedByUserAuth, other.gatedByUserAuth) && _deepEquals(userAuthType, other.userAuthType);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PgKeyInfo(alias: $alias, publicJwk: $publicJwk, securityLevel: $securityLevel, attestationType: $attestationType, gatedByUserAuth: $gatedByUserAuth, userAuthType: $userAuthType)';
  }
}

class PgCapabilities {
  PgCapabilities({
    required this.hasStrongBox,
    required this.hasTee,
    required this.hasSecureEnclave,
    required this.supportsKeyAttestation,
    required this.supportsBiometricGating,
    required this.bestAvailableLevel,
    this.androidApiLevel,
    this.iosVersion,
  });

  bool hasStrongBox;

  bool hasTee;

  bool hasSecureEnclave;

  bool supportsKeyAttestation;

  bool supportsBiometricGating;

  PgSecurityLevel bestAvailableLevel;

  int? androidApiLevel;

  String? iosVersion;

  List<Object?> _toList() {
    return <Object?>[
      hasStrongBox,
      hasTee,
      hasSecureEnclave,
      supportsKeyAttestation,
      supportsBiometricGating,
      bestAvailableLevel,
      androidApiLevel,
      iosVersion,
    ];
  }

  Object encode() {
    return _toList();  }

  static PgCapabilities decode(Object result) {
    result as List<Object?>;
    return PgCapabilities(
      hasStrongBox: result[0]! as bool,
      hasTee: result[1]! as bool,
      hasSecureEnclave: result[2]! as bool,
      supportsKeyAttestation: result[3]! as bool,
      supportsBiometricGating: result[4]! as bool,
      bestAvailableLevel: result[5]! as PgSecurityLevel,
      androidApiLevel: result[6] as int?,
      iosVersion: result[7] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PgCapabilities || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(hasStrongBox, other.hasStrongBox) && _deepEquals(hasTee, other.hasTee) && _deepEquals(hasSecureEnclave, other.hasSecureEnclave) && _deepEquals(supportsKeyAttestation, other.supportsKeyAttestation) && _deepEquals(supportsBiometricGating, other.supportsBiometricGating) && _deepEquals(bestAvailableLevel, other.bestAvailableLevel) && _deepEquals(androidApiLevel, other.androidApiLevel) && _deepEquals(iosVersion, other.iosVersion);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PgCapabilities(hasStrongBox: $hasStrongBox, hasTee: $hasTee, hasSecureEnclave: $hasSecureEnclave, supportsKeyAttestation: $supportsKeyAttestation, supportsBiometricGating: $supportsBiometricGating, bestAvailableLevel: $bestAvailableLevel, androidApiLevel: $androidApiLevel, iosVersion: $iosVersion)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is PgSecurityLevel) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is PgAttestationType) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is PgUserAuthType) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    }    else if (value is PgAttestationEncoding) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    }    else if (value is PgIosAccessibility) {
      buffer.putUint8(133);
      writeValue(buffer, value.index);
    }    else if (value is PgJwk) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is PgUserAuthPolicy) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    }    else if (value is PgAndroidKeyOptions) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    }    else if (value is PgIosKeyOptions) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    }    else if (value is PgGenerateKeyRequest) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    }    else if (value is PgGeneratedKey) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    }    else if (value is PgSignRequest) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    }    else if (value is PgSignature) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    }    else if (value is PgAttestRequest) {
      buffer.putUint8(142);
      writeValue(buffer, value.encode());
    }    else if (value is PgAttestation) {
      buffer.putUint8(143);
      writeValue(buffer, value.encode());
    }    else if (value is PgKeyInfo) {
      buffer.putUint8(144);
      writeValue(buffer, value.encode());
    }    else if (value is PgCapabilities) {
      buffer.putUint8(145);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : PgSecurityLevel.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : PgAttestationType.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : PgUserAuthType.values[value];
      case 132:
        final value = readValue(buffer) as int?;
        return value == null ? null : PgAttestationEncoding.values[value];
      case 133:
        final value = readValue(buffer) as int?;
        return value == null ? null : PgIosAccessibility.values[value];
      case 134:
        return PgJwk.decode(readValue(buffer)!);
      case 135:
        return PgUserAuthPolicy.decode(readValue(buffer)!);
      case 136:
        return PgAndroidKeyOptions.decode(readValue(buffer)!);
      case 137:
        return PgIosKeyOptions.decode(readValue(buffer)!);
      case 138:
        return PgGenerateKeyRequest.decode(readValue(buffer)!);
      case 139:
        return PgGeneratedKey.decode(readValue(buffer)!);
      case 140:
        return PgSignRequest.decode(readValue(buffer)!);
      case 141:
        return PgSignature.decode(readValue(buffer)!);
      case 142:
        return PgAttestRequest.decode(readValue(buffer)!);
      case 143:
        return PgAttestation.decode(readValue(buffer)!);
      case 144:
        return PgKeyInfo.decode(readValue(buffer)!);
      case 145:
        return PgCapabilities.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Every method carries
/// `@TaskQueue(type: TaskQueueType.serialBackgroundThread)`: Keystore /
/// Secure-Enclave work (key generation — seconds on StrongBox —, signing,
/// attestation chain serialization) is heavy and MUST NOT run on the Flutter
/// platform (main/UI) thread, where it would jank or trip an ANR. Pigeon
/// dispatches all annotated methods on a SINGLE shared serial background thread,
/// which both moves them off the UI thread AND serializes secure-hardware access
/// (Keymaster/StrongBox is single-flight anyway), giving deterministic ordering.
///
/// The biometric prompt is the one thing that must touch the UI thread; the
/// native `sign` implementation re-dispatches `BiometricPrompt.authenticate`
/// (Android) to the main thread itself, so gating still works transparently —
/// callers do nothing.
class AttestedSecureKeysApi {
  /// Constructor for [AttestedSecureKeysApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  AttestedSecureKeysApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Generate a NEW non-exportable EC P-256 key in the strongest available
  /// secure hardware. Throws (FlutterError code `unsupported_security_level`)
  /// if [PgGenerateKeyRequest.minSecurityLevel] cannot be met.
  Future<PgGeneratedKey> generateKey(PgGenerateKeyRequest request) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.attested_secure_keys.AttestedSecureKeysApi.generateKey$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as PgGeneratedKey;
  }

  /// ES256-sign the payload, returning raw 64-byte `R||S`.
  /// Triggers the OS biometric/PIN prompt when the key is auth-gated.
  Future<PgSignature> sign(PgSignRequest request) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.attested_secure_keys.AttestedSecureKeysApi.sign$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as PgSignature;
  }

  /// Produce a fresh attestation bound to the supplied server nonce.
  Future<PgAttestation> attest(PgAttestRequest request) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.attested_secure_keys.AttestedSecureKeysApi.attest$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as PgAttestation;
  }

  Future<PgKeyInfo?> getKeyInfo(String alias) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.attested_secure_keys.AttestedSecureKeysApi.getKeyInfo$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[alias]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as PgKeyInfo?;
  }

  Future<bool> containsKey(String alias) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.attested_secure_keys.AttestedSecureKeysApi.containsKey$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[alias]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<void> deleteKey(String alias) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.attested_secure_keys.AttestedSecureKeysApi.deleteKey$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[alias]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<List<String>> listAliases() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.attested_secure_keys.AttestedSecureKeysApi.listAliases$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<String>();
  }

  /// Probe what this device/OS can actually do, before generating anything.
  Future<PgCapabilities> capabilities() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.attested_secure_keys.AttestedSecureKeysApi.capabilities$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as PgCapabilities;
  }
}
